### ISSUE TITLE
Redeem token reverting with error: ERC20: burn amount exceeds balance

### ISSUE THREAD

**Issue by DennohKim** [GigaHierz/retire-carbon-credits-celo#3]
Hello @GigaHierz 

Thank you for the guide on how to use toucan sdk with celo composer.

I am having trouble redeeming or retiring tokens. Whats the reason for the transaction reverting with this error, ERC20: burn amount exceeds balance?

Your guidance and explanation will really help. Thank you.
![Screenshot from 2023-07-26 00-30-08](https://github.com/GigaHierz/retire-carbon-credits-celo/assets/63696529/9e5bf41e-c84b-4212-9d59-8824fd5afc92)

tx hash
0x86cec9bb0f48b6fee2e15be6eb77affc1525546a2cc924e568aacdf87cf541f2

kind regards

**Comment by GigaHierz** [comment]
Hi @DennohKim, 

looks like you are not holding any NCTs in your account, which you will need for redeeming for TCO2s, which you can then retire. Find more information on this in our [documentation](https://docs.toucan.earth/toucan/burn/compensating-for-emissions). For testing purposes, you can get them from our [Faucet](https://faucet.toucan.earth/). If you need NCTs on Mainnet, you will be able to buy them on [Uniswap](https://uniswap.org/) or on [Ubeswap](https://ubeswap.org/).

**Comment by DennohKim** [comment]
Thank you @GigaHierz . This is really helpful.
